version: "3.9"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - ./server:./
    env_file:
      - server.env