FROM golang:1.18.4-alpine

WORKDIR /go/bin

RUN go install github.com/canthefason/go-watcher/cmd/watcher@latest

WORKDIR /app
COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

ENTRYPOINT [ "/go/bin/watcher" ]